name: Docker Image CI

on:
  push:
    branches:
      - "main"
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: "${{ github.event.workflow_run_id % 60 }} ${{ github.event.workflow_run_id % 24 }} * * *"
    
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Determine Git tag
      id: git-tag
      run: echo "::set-output name=tag::$(git describe --exact-match --tags HEAD || echo '')"

    - name: Set tag if empty or invalid
      id: set-tag
      run: |
        if [ -z "${{ steps.git-tag.outputs.tag }}" ]; then
          echo "::set-output name=tag::latest"
        elif [[ "${{ steps.git-tag.outputs.tag }}" == *" "* ]]; then
          echo "::set-output name=tag::latest"
        else
          echo "::set-output name=tag::${{ steps.git-tag.outputs.tag }}"
        fi

    - name: Login to ghcr
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: ./2.4/
        file: ./2.4/Dockerfile
        platforms: linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64,linux/ppc64le,linux/s390x
        push: true
        tags: |
          ghcr.io/${{ github.actor }}/docker-webdav:latest
          ghcr.io/${{ github.actor }}/docker-webdav:${{ github.sha }}
          ghcr.io/${{ github.actor }}/docker-webdav:${{ steps.set-tag.outputs.tag }}
